export const VACCINE_TYPES = [
  'Karma (3\'lü)',
  'Karma (4\'lü)',
  'Kuduz',
  'FeLV',
  'FIV',
  'Klamidya',
  'Panleukopenia',
  'Diğer',
] as const;

export const CAT_BREEDS = [
  'Tekir',
  'Van Kedisi',
  'Ankara Kedisi',
  'British Shorthair',
  'Scottish Fold',
  'Persian',
  'Maine Coon',
  'Ragdoll',
  'Siamese',
  'Bengal',
  'Russian Blue',
  'Abyssinian',
  'Sphynx',
  'Norwegian Forest',
  'Turkish Angora',
  'Birman',
  'Devon Rex',
  'Burmese',
  'Himalayan',
  'American Shorthair',
  'Diğer',
] as const;
